[package]
name = "hrdf"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.31", features = ["serde"] }
regex = "1.10.2"
serde = { version = "1.0", features = ["derive", "rc"] }
strum = "0.25.0"
strum_macros = "0.25.3"

[profile.dev]
opt-level=3
