[package]
name = "hrdf"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
bincode = "1.3.3"
chrono = { version = "0.4.31", features = ["serde"] }
regex = "1.10.2"
rustc-hash = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
strum = "0.25.0"
strum_macros = "0.25.3"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread"] }

[profile.dev]
opt-level=3
